# SPDX-FileCopyrightText: 2020 Albert Krenz
#
# SPDX-License-Identifier: CC-BY-4.0

stages:
  - build
  - test

include:
  - template: Code-Quality.gitlab-ci.yml


debian:10:  
  image: "debian:10"
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y cmake ninja-build g++ libgtest-dev libgmock-dev libftdi1-dev libboost-dev libboost-program-options-dev libboost-log-dev
  script:
    - mkdir -p build
    - cd build
    - cmake -GNinja -DCOVERAGE=ON -DBUILD_TESTING=ON ..
    - ninja

opensuse:tumblewee:
  image: opensuse/tumbleweed
  before_script:
    - zypper refresh && zypper install --no-confirm boost-devel ninja cmake gcc-c++ gmock gtest libftdi1-devel libboost_program_options-devel libboost_log-devel libboost_thread-devel
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -GNinja -DCOVERAGE=ON -DBUILD_TESTING=ON ..
    - ninja 

unit_test:
  image: "gcc:10"
  stage: test
  script:
    - cd build
    - ctest --output-on-failure